# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 19:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bok_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Blah Blah Blah', max_length=50)),
                ('genre', models.IntegerField(default=10)),
                ('coverpage', models.ImageField(blank=True, null=True, upload_to='coverpage')),
                ('prologue', models.CharField(default='No Prologue available', max_length=1000)),
                ('publish', models.BooleanField(default=False)),
                ('no_of_likes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_no', models.IntegerField(default=1)),
                ('chapter_title', models.CharField(blank=True, max_length=20, null=True)),
                ('chapter_content', models.CharField(blank=True, max_length=3000, null=True)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('forum_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('user_name', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.IntegerField(default=10)),
                ('genre', models.CharField(default='General', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LikedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark', models.BooleanField(default=False)),
                ('bookmark_no', models.IntegerField(default=1)),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Book')),
                ('user_coll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=5000)),
                ('user_name', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2016, 10, 1, 19, 42, 20, 938043, tzinfo=utc))),
                ('forum_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Forum')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(blank=True, max_length=200, null=True)),
                ('blog', models.URLField(blank=True, max_length=100, null=True)),
                ('coverpic', models.ImageField(blank=True, null=True, upload_to='coverpic')),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='profilepic')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
